### PR TITLE
pyproject.toml inited

### PR DESCRIPTION
**Pull request by mikhail-akimov**
Since I only understand this functionality, I do not quite understand, is there an automated way to migrate from setup.py to poetry?

What is the correct action algorithm?

Do I need to install the application Jinja2_git to identify its dependencies for poetry?

Do I fill the dev-dependencies or not?

The range of the version of python, it turns out, is python = "~2.7 || ^3.6" (is it straight from the original poetry / pyproject.toml)?

### CODE REVIEW

**Comment by sobolevn** [comment]
@mikhail-akimov thanks! That's a good starting point. 
We will need to fix several things.

> Since I only understand this functionality, I do not quite understand, is there an automated way to migrate from setup.py to poetry?
No, currently there's no automated way to do it.

> What is the correct algorithm?
We just copy everything we need from `setup.py` to `pyproject.toml`.
Then we can delete `setup.py`.

> Do I need to install the application Jinja2_git to identify its dependencies for poetry?
No, you do not need to. There's only one dependency: https://github.com/sobolevn/jinja2-git/blob/master/setup.py#L13

> Do I fill the dev-dependencies or not?
Yes, we also need to install the dev-dependencies via `poetry`. You can find them here: https://github.com/sobolevn/jinja2-git/blob/master/tox.ini#L7-L20

Please, note that we do not need `delegator`.

**Comment by mikhail-akimov** [comment]
I did not understand what "Please, note that we do not need delegator." and "This is a WIP" means?

**Comment by sobolevn** [comment]
>  Please, note that we do not need delegator.
There was a dependency called `delegator`: https://github.com/sobolevn/jinja2-git/blob/master/tox.ini#L7 We do not need it anymore. So, it should be removed from the list.

> This is a WIP
It means that this pull request is "work in progress". So, it is not yet ready to be merged.

**Comment by mikhail-akimov** [comment]
Hello!

I finished the work on the issue (as i think :)). Did I do the right thing? Can I somehow influence the fact that Travis rejects my last commit?

**Comment by sobolevn** [comment]
I will merge this, but keep in mind that these changes break the CI. We will have to fix it in the next task.

**Pull request merged**
